sudo: false
language: c
addons:
  apt:
    packages:
    - libglib2.0-dev
    - gobject-introspection
    - gnome-common
    - autopoint
    - lcov
before_script: ./autogen.sh --enable-coverage
script:
  - make
  - make check
before_install:
  - pip install --user codecov
after_success:
  - codecov
